### PR TITLE
Use whitelist instead of blacklist

### PR DESCRIPTION
**Pull request by jakesen**
We only want to prerender partcycle domains (not provide free prerendering for others!)

### CODE REVIEW

**Comment by jakesen** [comment]
👀  @tyleryasaka

**Comment by tyleryasaka** [comment]
Ah!

**Comment by tyleryasaka** [comment]
Where to we "whitelist" partcycle.com?

**Comment by jakesen** [comment]
https://dashboard-classic.heroku.com/apps/partcycle-prerender/settings the ALLOWED_DOMAINS variable

**Comment by tyleryasaka** [comment]
Gotcha. 👍  to merge

**Pull request merged**
